apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  selector:
      matchLabels:
        app: nodeapp
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: vicohq/nodejstraining
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        livenessProbe: 
          httpGet:
            path: /status
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"